name: challenge-02

on: [push]

env:
  ARTIFACT_NAME: myartifact


jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: upload Artifact to linux
      uses: actions/upload-artifact@v2
      with:
        name: {{ env.ARTIFACT_NAME }}
        path: .
